name: flutter_bird_ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.dart"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
      coverage_excludes: "*.g.dart"
      min_coverage: 0 # Disables for now.
